import { Ionicons } from "@expo/vector-icons";
import { useLocalSearchParams, useRouter } from "expo-router";
import React, { useMemo, useState } from "react";
import { Alert, Image, Modal, SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useAppStore } from "../src/store";
import { getThemePalette } from "../src/theme";

const GROUPS: Record<string, any> = {
  mama: { name: "Mama Ajo Circle", amount: 25000, pot: 150000, paid: 4, date: "May 18, 2025", image: "https://i.pravatar.cc/100?img=12" },
  family: { name: "Family Lift", amount: 18000, pot: 108000, paid: 3, date: "May 25, 2025", image: "https://i.pravatar.cc/100?img=32" },
  weekend: { name: "December Trip ✈️", amount: 25000, pot: 150000, paid: 5, date: "June 1, 2025", image: "https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?auto=format&fit=crop&w=180&q=80" },
};
GROUPS.weekend = { name: "Weekend Savers", amount: 10000, pot: 60000, paid: 5, date: "June 1, 2025", image: "https://i.pravatar.cc/100?img=47" };
const ACTIVITY = [["You (Chigozie E.)", "Today, 9:41 AM", true, 11], ["Mina P.", "May 14, 2025", true, 47], ["Daniel O.", "May 13, 2025", true, 12], ["Kemi A.", "May 12, 2025", true, 25], ["Ebuka M.", "Awaiting payment", false, 33], ["Tobi L.", "Awaiting payment", false, 52]];
const money = (value: number) => `₦${value.toLocaleString("en-NG")}`;

export default function AjoDetails() {
  const router = useRouter();
  const { groupId } = useLocalSearchParams<{ groupId?: string }>();
  const group = GROUPS[groupId || "mama"] || GROUPS.mama;
  const { themePreference, themeMode } = useAppStore();
  const t = useMemo(() => getThemePalette(themePreference, themeMode), [themePreference, themeMode]);
  const [receipt, setReceipt] = useState<any>(null);

  return <SafeAreaView style={[s.safe, { backgroundColor: t.background }]}>
    <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={s.content}>
      <View style={s.nav}><TouchableOpacity onPress={() => router.back()} style={[s.navButton, { backgroundColor: t.surface }]}><Ionicons name="chevron-back" size={24} color={t.textPrimary} /></TouchableOpacity><TouchableOpacity style={[s.navButton, { backgroundColor: t.surface }]}><Ionicons name="ellipsis-horizontal" size={22} color={t.textPrimary} /></TouchableOpacity></View>
      <View style={s.hero}><Image source={{ uri: group.image }} style={[s.heroImage, { borderColor: t.surface }]} /><View style={s.titleLine}><Text style={[s.title, { color: t.textPrimary }]}>{group.name}</Text><Ionicons name="create-outline" size={19} color={t.accent} /></View><Text style={[s.sub, { color: t.textSecondary }]}>Private circle · 6 verified members</Text></View>
      <View style={[s.collection, { backgroundColor: t.surface, borderColor: t.border }]}>
        <View style={s.row}><Text style={[s.label, { color: t.textSecondary }]}>Next Collection</Text><Text style={[s.date, { color: t.accent }]}>{group.date}</Text></View>
        <View style={[s.row, { marginTop: 17, alignItems: "center" }]}><View><Text style={[s.amount, { color: t.textPrimary }]}>{money(group.amount)}</Text><Text style={[s.sub, { color: t.textSecondary }]}>My contribution</Text></View><View style={[s.next, { backgroundColor: t.accentSoft }]}><Ionicons name="ribbon" size={16} color={t.accent} /><Text style={[s.nextText, { color: t.accent }]}>You are next</Text></View></View>
        <View style={[s.rule, { backgroundColor: t.border }]} /><View style={s.row}><View><Text style={[s.label, { color: t.textSecondary }]}>Total Pot</Text><Text style={[s.pot, { color: t.textPrimary }]}>{money(group.pot)}</Text></View><View><Text style={[s.label, { color: t.textSecondary, textAlign: "right" }]}>Progress</Text><Text style={[s.pot, { color: t.textPrimary }]}>{group.paid}<Text style={{ color: t.textSecondary }}>/6 members</Text></Text></View></View><View style={[s.track, { backgroundColor: t.accentSoft }]}><View style={[s.fill, { backgroundColor: t.accent, width: `${group.paid / 6 * 100}%` }]} /></View><Text style={[s.percent, { color: t.textSecondary }]}>{Math.round(group.paid / 6 * 100)}% complete</Text>
      </View>
      <View style={[s.security, { backgroundColor: t.accentSoft }]}><Ionicons name="shield-checkmark-outline" size={22} color={t.accent} /><View style={{ flex: 1 }}><Text style={[s.securityTitle, { color: t.accent }]}>Protected Ajo circle</Text><Text style={[s.securityCopy, { color: t.textSecondary }]}>Only verified TallyTags can join. Every payment is recorded for all members.</Text></View></View>
      <Text style={[s.section, { color: t.textPrimary }]}>Ajo activity</Text><Text style={[s.sectionHint, { color: t.textSecondary }]}>Tap a completed payment to view its receipt.</Text>
      <View style={[s.activityList, { backgroundColor: t.surface, borderColor: t.border }]}>{ACTIVITY.map(([name, date, paid, avatar]) => <TouchableOpacity disabled={!paid} activeOpacity={0.75} onPress={() => paid && setReceipt({ name, date, amount: group.amount })} key={name as string} style={[s.activity, { borderBottomColor: t.border }]}><Image source={{ uri: `https://i.pravatar.cc/100?img=${avatar}` }} style={s.avatar} /><View style={{ flex: 1 }}><Text style={[s.memberName, { color: t.textPrimary }]}>{name}</Text><Text style={[s.memberStatus, { color: paid ? t.success : t.warning }]}>{paid ? "Paid · tap for receipt" : date}</Text></View><Ionicons name={paid ? "receipt-outline" : "remove-circle-outline"} size={20} color={paid ? t.accent : t.textSecondary} /></TouchableOpacity>)}</View>
      <TouchableOpacity onPress={() => Alert.alert("Contribution started", `Your ${money(group.amount)} contribution is ready to confirm.`)} style={[s.contribute, { backgroundColor: t.accent }]}><Ionicons name="arrow-up-circle" size={20} color="#fff" /><Text style={s.contributeText}>Make a Contribution</Text></TouchableOpacity>
      <TouchableOpacity onPress={() => Alert.alert("Leave Ajo Group", "Please contact the group administrator to leave this circle.")} style={s.leave}><Ionicons name="exit-outline" size={20} color={t.danger} /><Text style={[s.leaveText, { color: t.danger }]}>Leave Ajo Group</Text></TouchableOpacity>
    </ScrollView>
    <Modal transparent visible={!!receipt} animationType="fade" onRequestClose={() => setReceipt(null)}><View style={s.overlay}><View style={[s.receipt, { backgroundColor: t.surface }]}><View style={[s.receiptIcon, { backgroundColor: "#E9F7EF" }]}><Ionicons name="checkmark" size={26} color={t.success} /></View><Text style={[s.receiptTitle, { color: t.textPrimary }]}>Ajo payment receipt</Text><Text style={[s.receiptAmount, { color: t.textPrimary }]}>{receipt && money(receipt.amount)}</Text><Text style={[s.receiptCaption, { color: t.textSecondary }]}>Payment received from {receipt?.name}</Text><View style={[s.receiptRule, { backgroundColor: t.border }]} /><ReceiptRow label="Ajo circle" value={group.name} color={t.textPrimary} muted={t.textSecondary} /><ReceiptRow label="Date" value={receipt?.date} color={t.textPrimary} muted={t.textSecondary} /><ReceiptRow label="Status" value="Successful" color={t.success} muted={t.textSecondary} /><Text style={[s.reference, { color: t.textSecondary }]}>Ref: AJO-{String(receipt?.date).replace(/\W/g, "").slice(0, 8)}-TS</Text><TouchableOpacity onPress={() => setReceipt(null)} style={[s.done, { backgroundColor: t.accent }]}><Text style={s.doneText}>Done</Text></TouchableOpacity></View></View></Modal>
  </SafeAreaView>;
}
function ReceiptRow({ label, value, color, muted }: any) { return <View style={s.receiptRow}><Text style={[s.receiptLabel, { color: muted }]}>{label}</Text><Text style={[s.receiptValue, { color }]}>{value}</Text></View>; }
const s = StyleSheet.create({ safe:{flex:1},content:{padding:20,paddingBottom:36},nav:{flexDirection:"row",justifyContent:"space-between"},navButton:{height:44,width:44,borderRadius:13,alignItems:"center",justifyContent:"center"},hero:{alignItems:"center",marginTop:-5},heroImage:{width:94,height:94,borderRadius:47,borderWidth:4},titleLine:{flexDirection:"row",alignItems:"center",gap:9,marginTop:17},title:{fontSize:25,fontWeight:"800",letterSpacing:-.5},sub:{fontSize:13,marginTop:5},collection:{borderWidth:1,borderRadius:18,marginTop:29,padding:18},row:{flexDirection:"row",justifyContent:"space-between"},label:{fontSize:12},date:{fontSize:13,fontWeight:"800"},amount:{fontSize:26,fontWeight:"800"},next:{flexDirection:"row",gap:7,alignItems:"center",paddingHorizontal:11,paddingVertical:9,borderRadius:10},nextText:{fontSize:12,fontWeight:"800"},rule:{height:1,marginVertical:21},pot:{fontSize:17,fontWeight:"800",marginTop:5},track:{height:8,borderRadius:4,overflow:"hidden",marginTop:14},fill:{height:"100%",borderRadius:4},percent:{fontSize:12,marginTop:8},security:{borderRadius:16,padding:15,flexDirection:"row",gap:12,alignItems:"center",marginTop:20},securityTitle:{fontSize:13,fontWeight:"800"},securityCopy:{fontSize:11,lineHeight:16,marginTop:3},section:{fontSize:17,fontWeight:"800",marginTop:27},sectionHint:{fontSize:12,marginTop:4,marginBottom:12},activityList:{borderWidth:1,borderRadius:17,paddingHorizontal:14},activity:{flexDirection:"row",alignItems:"center",paddingVertical:12,borderBottomWidth:1},avatar:{width:43,height:43,borderRadius:22,marginRight:12},memberName:{fontSize:14,fontWeight:"800"},memberStatus:{fontSize:12,marginTop:4},contribute:{height:57,borderRadius:15,marginTop:24,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:9},contributeText:{color:"#fff",fontSize:15,fontWeight:"800"},leave:{flexDirection:"row",alignItems:"center",justifyContent:"center",gap:9,paddingVertical:24},leaveText:{fontSize:14,fontWeight:"800"},overlay:{flex:1,backgroundColor:"rgba(21,17,28,.43)",justifyContent:"center",padding:24},receipt:{borderRadius:24,padding:23},receiptIcon:{width:55,height:55,borderRadius:28,alignSelf:"center",alignItems:"center",justifyContent:"center"},receiptTitle:{fontSize:17,fontWeight:"800",textAlign:"center",marginTop:13},receiptAmount:{fontSize:30,fontWeight:"800",textAlign:"center",marginTop:10},receiptCaption:{fontSize:12,textAlign:"center",marginTop:6},receiptRule:{height:1,marginVertical:20},receiptRow:{flexDirection:"row",justifyContent:"space-between",marginBottom:13},receiptLabel:{fontSize:12},receiptValue:{fontSize:12,fontWeight:"800",maxWidth:"60%",textAlign:"right"},reference:{fontSize:10,textAlign:"center",marginTop:6},done:{height:50,borderRadius:14,alignItems:"center",justifyContent:"center",marginTop:20},doneText:{color:"#fff",fontWeight:"800"} });
