import { Ionicons } from "@expo/vector-icons";
import { useLocalSearchParams, useRouter } from "expo-router";
import React, { useState } from "react";
import { Alert, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { useAppStore } from "../src/store";
import { getThemePalette } from "../src/theme";

const periods = ["30 days", "3 months", "6 months", "1 year"];
export default function SavingsLockScreen() {
  const router = useRouter(); const { mode } = useLocalSearchParams<{ mode?: string }>(); const isJoint = mode === "joint";
  const { themePreference, themeMode } = useAppStore(); const theme = getThemePalette(themePreference, themeMode);
  const [amount, setAmount] = useState(""); const [period, setPeriod] = useState("3 months"); const [partner, setPartner] = useState("");
  const finish = () => { if (!amount.trim() || (isJoint && !partner.trim())) { Alert.alert("A little more detail", isJoint ? "Enter an amount and the TallyTag you want to save with." : "Enter the amount you want to lock."); return; } Alert.alert(isJoint ? "Invite ready" : "Lock created", isJoint ? `An invite to save toward this goal is ready for @${partner.replace(/^@/, "")}.` : `₦${amount} will be held safely for ${period}.`, [{ text: "Done", onPress: () => router.replace(isJoint ? "/joint-savings" : "/savingsprogress") }]); };
  return <SafeAreaView style={[s.safe, { backgroundColor: theme.background }]}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
    <View style={s.nav}><TouchableOpacity onPress={() => router.back()} style={[s.back, { backgroundColor: theme.surface }]}><Ionicons name="chevron-back" size={23} color={theme.textPrimary} /></TouchableOpacity><Text style={[s.navTitle, { color: theme.textPrimary }]}>{isJoint ? "New joint lock" : "New personal lock"}</Text><View style={{ width: 42 }} /></View>
    <View style={[s.hero, { backgroundColor: isJoint ? (themeMode === "dark" ? theme.surfaceSoft : "#21192A") : theme.accentSoft }]}><Ionicons name={isJoint ? "people-outline" : "lock-closed-outline"} size={25} color={isJoint ? "#fff" : theme.accent} /><Text style={[s.heroTitle, { color: isJoint ? "#fff" : theme.textPrimary }]}>{isJoint ? "Save together, without the guesswork." : "Put money aside and leave it there."}</Text><Text style={[s.heroCopy, { color: isJoint ? "rgba(255,255,255,.7)" : theme.textSecondary }]}>{isJoint ? "Both people see progress. The money stays locked until the agreed date." : "Choose an amount and date. Your money remains protected until it unlocks."}</Text></View>
    <Text style={[s.label, { color: theme.textPrimary }]}>How much are you locking?</Text><View style={[s.amountBox, { backgroundColor: theme.surface, borderColor: theme.border }]}><Text style={[s.naira, { color: theme.accent }]}>₦</Text><TextInput value={amount} onChangeText={setAmount} placeholder="0" placeholderTextColor={theme.textSecondary} keyboardType="numeric" style={[s.amountInput, { color: theme.textPrimary }]} /></View>
    {isJoint && <><Text style={[s.label, { color: theme.textPrimary }]}>Who are you saving with?</Text><View style={[s.textBox, { backgroundColor: theme.surface, borderColor: theme.border }]}><Ionicons name="at-outline" size={19} color={theme.accent} /><TextInput value={partner} onChangeText={setPartner} placeholder="Their TallyTag" placeholderTextColor={theme.textSecondary} autoCapitalize="none" style={[s.textInput, { color: theme.textPrimary }]} /></View><Text style={[s.helper, { color: theme.textSecondary }]}>They will confirm the shared target before any money is locked.</Text></>}
    <Text style={[s.label, { color: theme.textPrimary }]}>When should it unlock?</Text><View style={s.periods}>{periods.map((item) => <TouchableOpacity key={item} onPress={() => setPeriod(item)} style={[s.period, { backgroundColor: period === item ? theme.accent : theme.surface, borderColor: period === item ? theme.accent : theme.border }]}><Text style={[s.periodText, { color: period === item ? "#fff" : theme.textSecondary }]}>{item}</Text></TouchableOpacity>)}</View>
    <View style={[s.protection, { backgroundColor: theme.surfaceSoft }]}><Ionicons name="shield-checkmark-outline" size={19} color={theme.accent} /><Text style={[s.protectionText, { color: theme.textSecondary }]}>You will see the unlock date before you confirm. Locked savings cannot be used for spending.</Text></View>
    <TouchableOpacity onPress={finish} style={[s.continue, { backgroundColor: theme.accent }]}><Text style={s.continueText}>{isJoint ? "Send joint-saving invite" : "Review and lock"}</Text><Ionicons name="arrow-forward" size={18} color="#fff" /></TouchableOpacity>
  </ScrollView></SafeAreaView>;
}
const s = StyleSheet.create({ safe:{flex:1},content:{padding:20,paddingBottom:60},nav:{height:48,flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginBottom:13},back:{width:42,height:42,borderRadius:14,alignItems:"center",justifyContent:"center"},navTitle:{fontSize:17,fontWeight:"800"},hero:{borderRadius:23,padding:20,marginBottom:25},heroTitle:{fontSize:23,fontWeight:"800",lineHeight:29,letterSpacing:-.5,marginTop:14},heroCopy:{fontSize:12.5,lineHeight:18,marginTop:8},label:{fontSize:14,fontWeight:"800",marginBottom:9,marginTop:18},amountBox:{height:65,borderWidth:1,borderRadius:17,flexDirection:"row",alignItems:"center",paddingHorizontal:17},naira:{fontSize:25,fontWeight:"800",marginRight:9},amountInput:{fontSize:25,fontWeight:"800",flex:1,height:"100%"},textBox:{height:57,borderWidth:1,borderRadius:16,flexDirection:"row",alignItems:"center",gap:9,paddingHorizontal:15},textInput:{flex:1,fontSize:14,height:"100%",fontWeight:"600"},helper:{fontSize:11.5,lineHeight:16,marginTop:7},periods:{flexDirection:"row",flexWrap:"wrap",gap:8},period:{paddingHorizontal:14,paddingVertical:11,borderRadius:13,borderWidth:1},periodText:{fontSize:12,fontWeight:"700"},protection:{flexDirection:"row",gap:10,borderRadius:16,padding:14,marginTop:24},protectionText:{fontSize:11.5,lineHeight:17,flex:1},continue:{height:55,borderRadius:16,marginTop:21,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:9},continueText:{color:"#fff",fontSize:14,fontWeight:"800"} });
