import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import React, { useMemo, useState } from "react";
import { Alert, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { MOCK_RECIPIENTS, useAppStore } from "../src/store";
import { getThemePalette } from "../src/theme";

export default function AjoCreate() {
  const router = useRouter(); const { themePreference, themeMode } = useAppStore(); const t = useMemo(() => getThemePalette(themePreference, themeMode), [themePreference, themeMode]);
  const [name, setName] = useState(""); const [amount, setAmount] = useState(""); const [cycle, setCycle] = useState("Monthly"); const [tag, setTag] = useState(""); const [invites, setInvites] = useState<string[]>([]);
  const addTag = (value = tag) => { const normalized = value.trim().replace(/^@/, ""); if (!normalized) return; if (invites.includes(normalized)) return setTag(""); setInvites(current => [...current, normalized]); setTag(""); };
  const create = () => { if (!name.trim() || !amount.trim()) return Alert.alert("Complete your circle", "Enter a circle name and contribution amount."); if (invites.length < 2) return Alert.alert("Invite at least two people", "A secure Ajo circle needs you and at least two verified TallyTags."); Alert.alert("Ajo created", "Your private circle has been created. Invitations were sent only to the verified TallyTags you selected.", [{ text: "View my Ajos", onPress: () => router.replace("/ajo" as any) }]); };
  return <SafeAreaView style={[s.safe, { backgroundColor: t.background }]}><ScrollView keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false} contentContainerStyle={s.content}>
    <View style={s.header}><TouchableOpacity onPress={() => router.back()} style={[s.back, { backgroundColor: t.surface }]}><Ionicons name="chevron-back" size={23} color={t.textPrimary} /></TouchableOpacity><Text style={[s.title, { color: t.textPrimary }]}>Create Ajo</Text><View style={{ width: 42 }} /></View>
    <Text style={[s.hint, { color: t.textSecondary }]}>Set the contribution, then invite verified TallyTags.</Text>
    <Text style={[s.label, { color: t.textPrimary }]}>Circle details</Text><TextInput value={name} onChangeText={setName} placeholder="Circle name e.g. Weekend Savers" placeholderTextColor={t.textSecondary} style={[s.input, { color: t.textPrimary, backgroundColor: t.surface, borderColor: t.border }]} /><TextInput value={amount} onChangeText={setAmount} placeholder="Contribution amount e.g. ₦20,000" placeholderTextColor={t.textSecondary} keyboardType="numeric" style={[s.input, { color: t.textPrimary, backgroundColor: t.surface, borderColor: t.border, marginTop: 10 }]} />
    <Text style={[s.cycleLabel, { color: t.textSecondary }]}>Collection frequency</Text><View style={s.cycles}>{["Weekly", "Monthly", "Custom"].map(value => <TouchableOpacity key={value} onPress={() => setCycle(value)} style={[s.cycle, { borderColor: t.border, backgroundColor: cycle === value ? t.accent : t.surface }]}><Text style={[s.cycleText, { color: cycle === value ? "#fff" : t.textSecondary }]}>{value}</Text></TouchableOpacity>)}</View>
    <View style={s.inviteHeading}><View><Text style={[s.label, { color: t.textPrimary }]}>Invite with TallyTags</Text><Text style={[s.smallHint, { color: t.textSecondary }]}>Add at least 2 verified people</Text></View><Text style={[s.count, { color: t.accent }]}>{invites.length}/5</Text></View><View style={[s.tagInput, { backgroundColor: t.surface, borderColor: t.border }]}><Text style={[s.at, { color: t.accent }]}>@</Text><TextInput value={tag} onChangeText={setTag} onSubmitEditing={() => addTag()} placeholder="Enter a TallyTag" placeholderTextColor={t.textSecondary} autoCapitalize="none" style={[s.tagField, { color: t.textPrimary }]} /><TouchableOpacity onPress={() => addTag()} style={[s.add, { backgroundColor: t.accent }]}><Ionicons name="add" size={18} color="#fff" /></TouchableOpacity></View>
    <View style={s.suggestions}>{MOCK_RECIPIENTS.slice(0, 4).map(person => <TouchableOpacity key={person.id} onPress={() => addTag(person.username)} style={[s.suggestion, { backgroundColor: t.surfaceSoft }]}><Text style={[s.suggestionText, { color: t.accent }]}>@{person.username}</Text></TouchableOpacity>)}</View>
    {invites.length > 0 && <View style={s.invites}>{invites.map(item => <View key={item} style={[s.invite, { backgroundColor: t.surface, borderColor: t.border }]}><View style={[s.tagIcon, { backgroundColor: t.accentSoft }]}><Ionicons name="person-outline" size={17} color={t.accent} /></View><Text style={[s.inviteName, { color: t.textPrimary }]}>@{item}</Text><Text style={[s.verified, { color: t.success }]}>Verified</Text><TouchableOpacity onPress={() => setInvites(values => values.filter(value => value !== item))}><Ionicons name="close-circle" size={19} color={t.textSecondary} /></TouchableOpacity></View>)}</View>}
    <TouchableOpacity onPress={create} style={[s.create, { backgroundColor: t.accent }]}><Ionicons name="lock-closed-outline" size={17} color="#fff" /><Text style={s.createText}>Create Ajo</Text></TouchableOpacity>
  </ScrollView></SafeAreaView>;
}
const s = StyleSheet.create({ safe:{flex:1},content:{padding:20,paddingBottom:42},header:{flexDirection:"row",alignItems:"center",justifyContent:"space-between"},back:{width:42,height:42,borderRadius:13,justifyContent:"center",alignItems:"center"},title:{fontSize:18,fontWeight:"800"},intro:{fontSize:23,fontWeight:"800",marginTop:27,letterSpacing:-.3},hint:{fontSize:13,lineHeight:19,marginTop:7},security:{flexDirection:"row",gap:12,borderRadius:16,padding:15,marginTop:19,alignItems:"flex-start"},securityTitle:{fontSize:13,fontWeight:"800"},securityCopy:{fontSize:11,lineHeight:16,marginTop:3,maxWidth:280},label:{fontSize:15,fontWeight:"800",marginTop:27,marginBottom:10},input:{height:52,borderRadius:14,borderWidth:1,paddingHorizontal:14,fontSize:13},cycleLabel:{fontSize:12,fontWeight:"700",marginTop:17,marginBottom:8},cycles:{flexDirection:"row",gap:8},cycle:{flex:1,height:42,borderWidth:1,borderRadius:12,alignItems:"center",justifyContent:"center"},cycleText:{fontSize:12,fontWeight:"800"},inviteHeading:{flexDirection:"row",alignItems:"flex-end",justifyContent:"space-between",marginTop:8},smallHint:{fontSize:11},count:{fontSize:13,fontWeight:"800"},tagInput:{height:53,borderRadius:14,borderWidth:1,alignItems:"center",flexDirection:"row",paddingLeft:14},at:{fontSize:18,fontWeight:"800"},tagField:{flex:1,fontSize:13,paddingHorizontal:7},add:{width:38,height:38,borderRadius:11,alignItems:"center",justifyContent:"center",marginRight:7},suggestions:{flexDirection:"row",flexWrap:"wrap",gap:8,marginTop:11},suggestion:{paddingHorizontal:10,paddingVertical:7,borderRadius:9},suggestionText:{fontSize:11,fontWeight:"700"},invites:{marginTop:13,gap:8},invite:{height:54,borderRadius:14,borderWidth:1,flexDirection:"row",alignItems:"center",paddingHorizontal:11,gap:9},tagIcon:{width:31,height:31,borderRadius:10,alignItems:"center",justifyContent:"center"},inviteName:{flex:1,fontSize:13,fontWeight:"800"},verified:{fontSize:10,fontWeight:"800"},create:{height:54,borderRadius:15,marginTop:27,alignItems:"center",justifyContent:"center",flexDirection:"row",gap:9},createText:{color:"#fff",fontSize:14,fontWeight:"800"},footer:{fontSize:10,lineHeight:15,textAlign:"center",marginTop:12,paddingHorizontal:14} });
