import { Ionicons } from "@expo/vector-icons";
import { useLocalSearchParams, useRouter } from "expo-router";
import React, { useMemo } from "react";
import { Alert, Image, SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useAppStore } from "../src/store";
import { getThemePalette } from "../src/theme";

const GOALS: Record<string, { goal: string; saved: number; target: number; partner: string; due: string; lock: string }> = {
  "joint-1": { goal: "New laptop", saved: 165000, target: 300000, partner: "Titi", due: "4 months left", lock: "Unlocks 30 Dec 2026" },
  "joint-2": { goal: "Holiday trip", saved: 284000, target: 480000, partner: "Bolu", due: "6 months left", lock: "Unlocks 14 Feb 2027" },
  "joint-3": { goal: "Home setup", saved: 112500, target: 200000, partner: "Chika", due: "3 months left", lock: "Unlocks 30 Nov 2026" },
};

export default function JointSavingsDetails() {
  const router = useRouter(); const { id } = useLocalSearchParams<{ id?: string }>();
  const { themePreference, themeMode } = useAppStore(); const theme = getThemePalette(themePreference, themeMode);
  const goal = GOALS[id || "joint-1"] || GOALS["joint-1"]; const progress = useMemo(() => Math.round(goal.saved / goal.target * 100), [goal]);
  return <SafeAreaView style={[s.safe, { backgroundColor: theme.background }]}><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
    <View style={s.nav}><TouchableOpacity onPress={() => router.back()} style={[s.navBtn, { backgroundColor: theme.surface }]}><Ionicons name="chevron-back" size={24} color={theme.textPrimary} /></TouchableOpacity><TouchableOpacity style={[s.navBtn, { backgroundColor: theme.surface }]}><Ionicons name="ellipsis-horizontal" size={21} color={theme.textPrimary} /></TouchableOpacity></View>
    <View style={[s.hero, { backgroundColor: theme.accent }]}><View style={s.lockRow}><Ionicons name="lock-closed" size={14} color="#fff" /><Text style={s.lockLabel}>JOINT LOCK</Text></View><Text style={s.goalTitle}>{goal.goal}</Text><Text style={s.partner}>With {goal.partner} · shared goal</Text><Text style={s.saved}>₦{goal.saved.toLocaleString()}</Text><Text style={s.ofTarget}>of ₦{goal.target.toLocaleString()} target</Text><View style={s.track}><View style={[s.fill, { width: `${progress}%`, backgroundColor: theme.accentSoft }]} /></View><View style={s.progressRow}><Text style={s.progress}>{progress}% funded</Text><Text style={s.progress}>{goal.due}</Text></View></View>
    <View style={[s.unlock, { backgroundColor: theme.accentSoft }]}><View style={[s.unlockIcon, { backgroundColor: theme.accent }]}><Ionicons name="time-outline" size={18} color="#fff" /></View><View style={{ flex: 1 }}><Text style={[s.unlockTitle, { color: theme.textPrimary }]}>{goal.lock}</Text><Text style={[s.unlockCopy, { color: theme.textSecondary }]}>Funds can only be released when both members approve after this date.</Text></View></View>
    <Text style={[s.sectionTitle, { color: theme.textPrimary }]}>Contributions</Text><View style={[s.memberList, { backgroundColor: theme.surface, borderColor: theme.border }]}>
      <Member name="Chigozie" tag="@chigozie" amount="₦90,000" pace="On track" image="https://i.pravatar.cc/100?img=11" color={theme.accent} bg={theme.accentSoft} text={theme.textPrimary} muted={theme.textSecondary} />
      <Member name={goal.partner} tag={`@${goal.partner.toLowerCase()}saves`} amount={`₦${(goal.saved - 90000).toLocaleString()}`} pace="On track" image={id === "joint-2" ? "https://i.pravatar.cc/100?img=27" : id === "joint-3" ? "https://i.pravatar.cc/100?img=41" : "https://i.pravatar.cc/100?img=15"} color={theme.success} bg={theme.surfaceSoft} text={theme.textPrimary} muted={theme.textSecondary} />
    </View>
    <TouchableOpacity onPress={() => Alert.alert("Add to joint lock", "Choose an amount to add from your available balance.")} style={[s.primary, { backgroundColor: theme.accent }]}><Ionicons name="add" size={20} color="#fff" /><Text style={s.primaryText}>Add money</Text></TouchableOpacity>
    <Text style={[s.footer, { color: theme.textSecondary }]}>Every contribution is visible to both members. Locked funds cannot be spent early.</Text>
  </ScrollView></SafeAreaView>;
}
function Member({ name, tag, amount, pace, image, color, text, muted }: any) { return <View style={s.member}><Image source={{ uri: image }} style={s.memberAvatar} /><View style={{ flex: 1 }}><Text style={[s.memberName, { color: text }]}>{name}</Text><Text style={[s.memberTag, { color: muted }]}>{tag} · <Text style={{ color }}>{pace}</Text></Text></View><Text style={[s.memberAmount, { color: text }]}>{amount}</Text></View>; }
const s = StyleSheet.create({ safe:{flex:1},content:{padding:20,paddingBottom:100},nav:{flexDirection:"row",justifyContent:"space-between",marginBottom:17},navBtn:{height:42,width:42,borderRadius:14,alignItems:"center",justifyContent:"center"},hero:{borderRadius:26,padding:22},lockRow:{flexDirection:"row",alignItems:"center",gap:7},lockLabel:{color:"#fff",fontSize:10,fontWeight:"800",letterSpacing:1},goalTitle:{color:"#fff",fontSize:27,fontWeight:"800",letterSpacing:-.7,marginTop:20},partner:{color:"rgba(255,255,255,.68)",fontSize:13,marginTop:5},saved:{color:"#fff",fontSize:30,fontWeight:"800",marginTop:27},ofTarget:{color:"rgba(255,255,255,.66)",fontSize:12,marginTop:3},track:{height:8,borderRadius:4,backgroundColor:"rgba(255,255,255,.18)",marginTop:17,overflow:"hidden"},fill:{height:"100%",borderRadius:4},progressRow:{flexDirection:"row",justifyContent:"space-between",marginTop:8},progress:{color:"rgba(255,255,255,.8)",fontSize:11,fontWeight:"700"},unlock:{borderRadius:18,padding:15,flexDirection:"row",gap:11,marginTop:17,alignItems:"center"},unlockIcon:{width:38,height:38,borderRadius:12,alignItems:"center",justifyContent:"center"},unlockTitle:{fontSize:13.5,fontWeight:"800"},unlockCopy:{fontSize:11.5,lineHeight:16,marginTop:3},sectionTitle:{fontSize:17,fontWeight:"800",marginTop:27,marginBottom:11},memberList:{borderWidth:1,borderRadius:18,paddingHorizontal:15},member:{flexDirection:"row",alignItems:"center",paddingVertical:14,borderBottomWidth:0},memberAvatar:{height:42,width:42,borderRadius:21,marginRight:11},memberName:{fontSize:14,fontWeight:"800"},memberTag:{fontSize:11.5,fontWeight:"600",marginTop:3},memberAmount:{fontSize:13,fontWeight:"800"},primary:{height:55,borderRadius:16,marginTop:21,flexDirection:"row",justifyContent:"center",alignItems:"center",gap:8},primaryText:{color:"#fff",fontSize:15,fontWeight:"800"},footer:{fontSize:11.5,lineHeight:17,textAlign:"center",marginTop:14,paddingHorizontal:14} });
