import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import React, { useMemo } from "react";
import { SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useAppStore } from "../src/store";
import { getThemePalette } from "../src/theme";

const goals = [
  { name: "Emergency reserve", current: 820000, target: 1200000, date: "Ongoing", icon: "shield-checkmark-outline" as const },
  { name: "New laptop", current: 450000, target: 900000, date: "December 2026", icon: "laptop-outline" as const },
  { name: "December holiday", current: 180000, target: 300000, date: "November 2026", icon: "airplane-outline" as const },
];

export default function SavingsProgressScreen() {
  const router = useRouter(); const { themePreference, themeMode } = useAppStore(); const theme = getThemePalette(themePreference, themeMode);
  const summary = useMemo(() => goals.reduce((total, goal) => ({ current: total.current + goal.current, target: total.target + goal.target }), { current: 0, target: 0 }), []); const percent = Math.round(summary.current / summary.target * 100);
  return <SafeAreaView style={[s.safe, { backgroundColor: theme.background }]}>
    <View style={s.header}><TouchableOpacity onPress={() => router.back()} style={[s.back, { backgroundColor: theme.surface, borderColor: theme.border }]}><Ionicons name="chevron-back" size={23} color={theme.textPrimary} /></TouchableOpacity><Text style={[s.title, { color: theme.textPrimary }]}>Savings</Text><TouchableOpacity onPress={() => router.push({ pathname: "/savings-lock", params: { mode: "personal" } })} style={[s.add, { borderColor: theme.accent }]}><Ionicons name="add" size={19} color={theme.accent} /><Text style={[s.addText, { color: theme.accent }]}>Add</Text></TouchableOpacity></View>
    <ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
      <View style={[s.switcher, { backgroundColor: theme.surfaceSoft }]}><View style={[s.activeTab, { backgroundColor: theme.surface }]}><Text style={[s.activeTabText, { color: theme.accent }]}>My savings</Text></View><TouchableOpacity onPress={() => router.push("/joint-savings")} style={s.tab}><Text style={[s.tabText, { color: theme.textSecondary }]}>Joint savings</Text></TouchableOpacity></View>
      <View style={[s.totalCard, { backgroundColor: theme.surface, borderColor: theme.border }]}><View style={s.cardTop}><View><Text style={[s.overline, { color: theme.textSecondary }]}>TOTAL SAVED</Text><Text style={[s.total, { color: theme.textPrimary }]}>₦{summary.current.toLocaleString()}</Text></View><View style={[s.lockIcon, { backgroundColor: theme.accentSoft }]}><Ionicons name="lock-closed-outline" size={20} color={theme.accent} /></View></View><Text style={[s.target, { color: theme.textSecondary }]}>of ₦{summary.target.toLocaleString()} across your goals</Text><View style={[s.track, { backgroundColor: theme.surfaceSoft }]}><View style={[s.fill, { backgroundColor: theme.accent, width: `${percent}%` }]} /></View><Text style={[s.progress, { color: theme.accent }]}>{percent}% funded</Text></View>
      <TouchableOpacity onPress={() => router.push({ pathname: "/savings-lock", params: { mode: "personal" } })} style={[s.lockAction, { backgroundColor: theme.accent }]}><View><Text style={s.lockActionTitle}>Start a personal lock</Text><Text style={s.lockActionCopy}>Choose an amount and unlock date.</Text></View><Ionicons name="arrow-forward" size={19} color="#fff" /></TouchableOpacity>
      <View style={s.sectionHead}><Text style={[s.section, { color: theme.textSecondary }]}>MY GOALS</Text><TouchableOpacity onPress={() => router.push("/joint-savings")}><Text style={[s.jointLink, { color: theme.accent }]}>Save with someone</Text></TouchableOpacity></View>
      <View style={[s.list, { backgroundColor: theme.surface, borderColor: theme.border }]}>{goals.map((goal, index) => { const progress = Math.round(goal.current / goal.target * 100); return <TouchableOpacity key={goal.name} activeOpacity={0.78} style={[s.goal, index < goals.length - 1 && { borderBottomWidth: 1, borderBottomColor: theme.border }]}><View style={[s.goalIcon, { backgroundColor: theme.accentSoft }]}><Ionicons name={goal.icon} size={19} color={theme.accent} /></View><View style={{ flex: 1 }}><View style={s.goalTitleRow}><Text style={[s.goalName, { color: theme.textPrimary }]}>{goal.name}</Text><Text style={[s.goalPercent, { color: theme.accent }]}>{progress}%</Text></View><Text style={[s.goalSub, { color: theme.textSecondary }]}>₦{goal.current.toLocaleString()} of ₦{goal.target.toLocaleString()} · {goal.date}</Text><View style={[s.goalTrack, { backgroundColor: theme.surfaceSoft }]}><View style={[s.goalFill, { backgroundColor: theme.accent, width: `${progress}%` }]} /></View></View><Ionicons name="chevron-forward" size={16} color={theme.textSecondary} /></TouchableOpacity>; })}</View>
      <View style={[s.note, { backgroundColor: theme.accentSoft }]}><Ionicons name="shield-checkmark-outline" size={17} color={theme.accent} /><Text style={[s.noteText, { color: theme.textSecondary }]}>Your locked money stays protected until its selected unlock date.</Text></View>
    </ScrollView>
  </SafeAreaView>;
}
const s = StyleSheet.create({ safe:{flex:1},header:{height:68,flexDirection:"row",justifyContent:"space-between",alignItems:"center",paddingHorizontal:20},back:{height:42,width:42,borderRadius:14,alignItems:"center",justifyContent:"center",borderWidth:1},title:{fontSize:22,fontWeight:"800",letterSpacing:-.4},add:{height:42,borderRadius:12,borderWidth:1.5,paddingHorizontal:11,flexDirection:"row",gap:5,alignItems:"center",justifyContent:"center"},addText:{fontSize:12,fontWeight:"800"},content:{padding:20,paddingTop:12,paddingBottom:110},switcher:{height:48,borderRadius:15,padding:4,flexDirection:"row",marginBottom:18},activeTab:{flex:1,borderRadius:11,alignItems:"center",justifyContent:"center",shadowColor:"#000",shadowOpacity:.04,shadowRadius:4,elevation:1},tab:{flex:1,alignItems:"center",justifyContent:"center"},activeTabText:{fontSize:13,fontWeight:"800"},tabText:{fontSize:13,fontWeight:"700"},totalCard:{borderRadius:24,borderWidth:1,padding:20},cardTop:{flexDirection:"row",justifyContent:"space-between",alignItems:"flex-start"},overline:{fontSize:10.5,fontWeight:"800",letterSpacing:1},total:{fontSize:30,fontWeight:"800",letterSpacing:-.8,marginTop:10},lockIcon:{height:43,width:43,borderRadius:14,alignItems:"center",justifyContent:"center"},target:{fontSize:12.5,marginTop:5},track:{height:8,borderRadius:4,marginTop:18,overflow:"hidden"},fill:{height:"100%",borderRadius:4},progress:{fontSize:12,fontWeight:"800",marginTop:8},lockAction:{minHeight:74,borderRadius:19,marginTop:15,paddingHorizontal:18,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},lockActionTitle:{color:"#fff",fontSize:14,fontWeight:"800"},lockActionCopy:{color:"rgba(255,255,255,.7)",fontSize:11.5,marginTop:3},sectionHead:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginTop:29,marginBottom:11,paddingHorizontal:3},section:{fontSize:11,fontWeight:"800",letterSpacing:1},jointLink:{fontSize:12,fontWeight:"800"},list:{borderRadius:21,borderWidth:1,paddingHorizontal:15},goal:{flexDirection:"row",alignItems:"center",gap:11,paddingVertical:14},goalIcon:{height:42,width:42,borderRadius:14,alignItems:"center",justifyContent:"center"},goalTitleRow:{flexDirection:"row",justifyContent:"space-between",gap:5},goalName:{fontSize:14,fontWeight:"800"},goalPercent:{fontSize:12,fontWeight:"800"},goalSub:{fontSize:11.2,marginTop:4},goalTrack:{height:4,borderRadius:2,overflow:"hidden",marginTop:8},goalFill:{height:"100%",borderRadius:2},note:{flexDirection:"row",gap:9,borderRadius:16,padding:14,marginTop:16},noteText:{fontSize:11.5,lineHeight:16,flex:1} });
